[ci] Fix Python3.6 issue on Linux x86
This patch fixes the following issue:

```
Error: Version 3.6 with arch x64 not found
```

Cause: there is no available build of Python 3.6 for ubuntu-22.04

ref: https://github.com/actions/setup-python/issues/544

Signed-off-by: Gael Chamoulaud (Strider) <gchamoul@redhat.com>